version: '3.8'

services:
  # Enhanced Storage Service - Main Application
  enhanced-storage-service:
    build:
      context: ./enhanced_storage_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      # Use existing TracSeq database
      - DATABASE_URL=postgres://postgres:postgres@db:5432/lab_manager
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - PORT=8082
      - HOST=0.0.0.0
      
      # Integration with existing services
      - AUTH_SERVICE_URL=http://auth-service:8080
      - SAMPLE_SERVICE_URL=http://sample-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8085
      - EVENT_SERVICE_URL=http://event-service:8087
      
      # Storage configuration
      - STORAGE_PATH=/app/storage
      - BACKUP_PATH=/app/backups
      
      # Security
      - JWT_SECRET=enhanced-storage-tracseq-integration-2024
      - ENCRYPTION_KEY=enhanced-storage-encryption-key-32bit
      
      # Mock integrations for development
      - LIMS_BASE_URL=http://mock-lims:8090
      - ERP_BASE_URL=http://mock-erp:8091
      - MOCK_SERVICES_ENABLED=true
      
    volumes:
      - enhanced_storage_data:/app/storage
      - enhanced_backup_data:/app/backups
    depends_on:
      - db
      - redis-enhanced
    networks:
      - lab_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis for Enhanced Storage (separate from main Redis if needed)
  redis-enhanced:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_enhanced_data:/data
    networks:
      - lab_network
    restart: unless-stopped

  # Mock LIMS Service for testing enterprise integration
  mock-lims:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8090:8080"
    command: --global-response-templating --verbose
    volumes:
      - ./enhanced_storage_service/mocks/lims:/home/wiremock
    networks:
      - lab_network
    restart: unless-stopped

  # Mock ERP Service for testing enterprise integration  
  mock-erp:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8091:8080"
    command: --global-response-templating --verbose
    volumes:
      - ./enhanced_storage_service/mocks/erp:/home/wiremock
    networks:
      - lab_network
    restart: unless-stopped

  # Enhanced Grafana with Enhanced Storage dashboards
  grafana-enhanced:
    image: grafana/grafana:10.1.0
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_enhanced_data:/var/lib/grafana
    networks:
      - lab_network
    restart: unless-stopped

volumes:
  enhanced_storage_data:
  enhanced_backup_data:
  redis_enhanced_data:
  grafana_enhanced_data:

networks:
  lab_network:
    external: true 
