version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: tracseq_postgres
    env_file:
      - config/development.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lab_manager}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - tracseq_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: tracseq_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tracseq_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Dashboard Service (Python)
  dashboard-service:
    build:
      context: ./simple-services/dashboard-service
      dockerfile: Dockerfile
    container_name: tracseq_dashboard
    env_file:
      - config/development.env
    ports:
      - "${DASHBOARD_SERVICE_PORT:-8080}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/lab_manager}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    volumes:
      - app_logs:/app/logs
      - app_uploads:/app/uploads
      - app_storage:/app/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tracseq_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Samples Service (Python)
  samples-service:
    build:
      context: ./simple-services/samples-service
      dockerfile: Dockerfile
    container_name: tracseq_samples
    env_file:
      - config/development.env
    ports:
      - "${SAMPLES_SERVICE_PORT:-8081}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/lab_manager}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    volumes:
      - app_logs:/app/logs
      - app_uploads:/app/uploads
      - app_storage:/app/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tracseq_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Sequencing Service (Python)
  sequencing-service:
    build:
      context: ./simple-services/sequencing-service
      dockerfile: Dockerfile
    container_name: tracseq_sequencing
    env_file:
      - config/development.env
    ports:
      - "${SEQUENCING_SERVICE_PORT:-8082}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/lab_manager}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    volumes:
      - app_logs:/app/logs
      - app_uploads:/app/uploads
      - app_storage:/app/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tracseq_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Spreadsheet Service (Python)
  spreadsheet-service:
    build:
      context: ./simple-services/spreadsheet-service
      dockerfile: Dockerfile
    container_name: tracseq_spreadsheet
    env_file:
      - config/development.env
    ports:
      - "${SPREADSHEET_SERVICE_PORT:-8083}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/lab_manager}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    volumes:
      - app_logs:/app/logs
      - app_uploads:/app/uploads
      - templates_data:/app/templates
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tracseq_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend Proxy Service (Python)
  frontend-proxy:
    build:
      context: ./simple-services/frontend-proxy
      dockerfile: Dockerfile
    container_name: tracseq_frontend_proxy
    env_file:
      - config/development.env
    ports:
      - "${FRONTEND_PROXY_PORT:-8084}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/lab_manager}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DASHBOARD_SERVICE_URL=http://dashboard-service:8080
      - SAMPLES_SERVICE_URL=http://samples-service:8080
      - SEQUENCING_SERVICE_URL=http://sequencing-service:8080
      - SPREADSHEET_SERVICE_URL=http://spreadsheet-service:8080
      - API_GATEWAY_URL=http://api-gateway:8000
    volumes:
      - app_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      dashboard-service:
        condition: service_healthy
      samples-service:
        condition: service_healthy
      sequencing-service:
        condition: service_healthy
      spreadsheet-service:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    networks:
      - tracseq_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # API Gateway Service (Simple Python)
  api-gateway:
    build:
      context: ./simple-services/api-gateway
      dockerfile: Dockerfile
    container_name: tracseq_api_gateway
    env_file:
      - config/development.env
    ports:
      - "${API_GATEWAY_PORT:-8089}:8000"
    environment:
      - DASHBOARD_SERVICE_URL=http://dashboard-service:8080
      - SAMPLES_SERVICE_URL=http://samples-service:8080
      - SEQUENCING_SERVICE_URL=http://sequencing-service:8080
      - SPREADSHEET_SERVICE_URL=http://spreadsheet-service:8080
    
    volumes:
      - app_logs:/app/logs
    
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      dashboard-service:
        condition: service_healthy
      samples-service:
        condition: service_healthy
      sequencing-service:
        condition: service_healthy
      spreadsheet-service:
        condition: service_healthy
    
    networks:
      - tracseq_network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  # Database and cache persistence
  postgres_data:
    driver: local
  redis_data:
    driver: local
  
  # Application data persistence
  app_storage:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local
  
  # Template and configuration persistence
  templates_data:
    driver: local
  
  # Development cache volumes
  node_modules:
    driver: local
  cargo_cache:
    driver: local

networks:
  tracseq_network:
    driver: bridge 