apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: tracseq
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/part-of: tracseq
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
      app.kubernetes.io/component: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
        app.kubernetes.io/component: auth-service
        app.kubernetes.io/part-of: tracseq
    spec:
      serviceAccountName: tracseq-auth-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        env:
        - name: SERVICE_NAME
          value: "auth-service"
        - name: SERVICE_PORT
          value: "8080"
        # Database configuration
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tracseq-database-credentials
              key: AUTH_DATABASE_URL
        # Redis configuration
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: tracseq-database-credentials
              key: REDIS_URL
        # JWT configuration
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tracseq-jwt-secret
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: tracseq-jwt-secret
              key: JWT_ALGORITHM
        - name: JWT_EXPIRATION_HOURS
          valueFrom:
            secretKeyRef:
              name: tracseq-jwt-secret
              key: JWT_EXPIRATION_HOURS
        # Common configuration from ConfigMap
        envFrom:
        - configMapRef:
            name: tracseq-common-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: temp
          mountPath: /tmp
      volumes:
      - name: temp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: tracseq
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/part-of: tracseq
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: auth-service
  sessionAffinity: None