global:
  resolve_timeout: 5m
  # Slack webhook URL (replace with your actual webhook)
  # slack_api_url: 'YOUR_SLACK_WEBHOOK_URL'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: critical-receiver
      continue: true
    - match:
        severity: warning
      receiver: warning-receiver

receivers:
  - name: 'default-receiver'
    # webhook_configs:
    #   - url: 'http://localhost:5001/webhook'

  - name: 'critical-receiver'
    # email_configs:
    #   - to: 'admin@example.com'
    #     from: 'alertmanager@example.com'
    #     smarthost: 'smtp.example.com:587'
    #     auth_username: 'alertmanager@example.com'
    #     auth_password: 'password'
    # slack_configs:
    #   - channel: '#alerts-critical'
    #     title: 'Critical Alert'
    #     text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: 'warning-receiver'
    # slack_configs:
    #   - channel: '#alerts-warning'
    #     title: 'Warning Alert'
    #     text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']