services:
  # Enhanced Services that extend the base deployment
  notification-service:
    image: tracseq-notification_service:latest
    container_name: lims-notification
    environment:
      DATABASE_URL: postgres://postgres:postgres@lims-postgres:5432/lims_db
      REDIS_URL: redis://lims-redis:6379
      NOTIFICATION_PORT: "8000"
      JWT_SECRET: "your-jwt-secret"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: "noreply@tracseq.com"
      SMTP_PASSWORD: ""
    ports:
      - "8015:8000"
    networks:
      - lims-network
    external_links:
      - lims-postgres:postgres
      - lims-redis:redis

  event-service:
    image: tracseq-event_service:latest
    container_name: lims-events
    environment:
      DATABASE_URL: postgres://postgres:postgres@lims-postgres:5432/lims_db
      REDIS_URL: redis://lims-redis:6379
      EVENT_PORT: "8000"
      JWT_SECRET: "your-jwt-secret"
    ports:
      - "8016:8000"
    networks:
      - lims-network
    external_links:
      - lims-postgres:postgres
      - lims-redis:redis

  transaction-service:
    image: tracseq-transaction_service:latest
    container_name: lims-transactions
    environment:
      DATABASE_URL: postgres://postgres:postgres@lims-postgres:5432/lims_db
      REDIS_URL: redis://lims-redis:6379
      TRANSACTION_PORT: "8000"
      JWT_SECRET: "your-jwt-secret"
    ports:
      - "8017:8000"
    networks:
      - lims-network
    external_links:
      - lims-postgres:postgres
      - lims-redis:redis

  template-service:
    image: tracseq-template_service:latest
    container_name: lims-templates
    environment:
      DATABASE_URL: postgres://postgres:postgres@lims-postgres:5432/lims_db
      REDIS_URL: redis://lims-redis:6379
      TEMPLATE_PORT: "8000"
      JWT_SECRET: "your-jwt-secret"
    ports:
      - "8018:8000"
    networks:
      - lims-network
    external_links:
      - lims-postgres:postgres
      - lims-redis:redis

  sequencing-service:
    image: tracseq-sequencing_service:latest
    container_name: lims-sequencing
    environment:
      DATABASE_URL: postgres://postgres:postgres@lims-postgres:5432/lims_db
      REDIS_URL: redis://lims-redis:6379
      SEQUENCING_PORT: "8000"
      JWT_SECRET: "your-jwt-secret"
    ports:
      - "8019:8000"
    networks:
      - lims-network
    external_links:
      - lims-postgres:postgres
      - lims-redis:redis

  qaqc-service:
    image: tracseq-qaqc_service:latest
    container_name: lims-qaqc
    environment:
      DATABASE_URL: postgres://postgres:postgres@lims-postgres:5432/lims_db
      REDIS_URL: redis://lims-redis:6379
      QAQC_PORT: "8000"
      JWT_SECRET: "your-jwt-secret"
      DEFAULT_QUALITY_THRESHOLD: "80.0"
      ENABLE_REAL_TIME_MONITORING: "true"
      COMPLIANCE_STANDARDS: "ISO15189,CLIA,CAP,GLP"
    ports:
      - "8020:8000"
    networks:
      - lims-network
    external_links:
      - lims-postgres:postgres
      - lims-redis:redis

networks:
  lims-network:
    external: true
    name: docker_lims-network 