services:
  postgres:
    image: postgres:15-alpine
    container_name: tracseq-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tracseq_main
      POSTGRES_USER: tracseq_admin
      POSTGRES_PASSWORD: tracseq_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tracseq_admin -d tracseq_main"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tracseq-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --requirepass tracseq_redis_password
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "tracseq_redis_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge
