apiVersion: v1
kind: Namespace
metadata:
  name: tracseq
  labels:
    app.kubernetes.io/name: tracseq
    app.kubernetes.io/part-of: tracseq-platform
  annotations:
    openshift.io/description: "TracSeq 2.0 Laboratory Management System"
    openshift.io/display-name: "TracSeq Production"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tracseq-quota
  namespace: tracseq
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "20"
    services: "50"
    configmaps: "100"
    secrets: "100"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tracseq-limits
  namespace: tracseq
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      storage: "100Gi"
    type: PersistentVolumeClaim