# Database Connection Pool Configuration
postgres:
  max_connections: 100
  min_connections: 10
  connection_timeout: 30s
  idle_timeout: 900s
  max_lifetime: 3600s

redis:
  pool_size: 50
  connection_timeout: 5s
  read_timeout: 5s
  write_timeout: 5s
