global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TracSeq Microservices
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'sample-service'
    static_configs:
      - targets: ['sample-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'template-service'
    static_configs:
      - targets: ['template-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'enhanced-rag-service'
    static_configs:
      - targets: ['enhanced-rag-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Infrastructure
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
