# TracSeq 2.0 Phase 6 Prometheus Configuration
# Complete monitoring setup for all microservices

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'tracseq-2.0'
    environment: 'development'

rule_files:
  - "/etc/prometheus/alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TracSeq Microservices
  - job_name: 'tracseq-auth-service'
    static_configs:
      - targets: ['host.docker.internal:3010']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'tracseq-template-service'
    static_configs:
      - targets: ['host.docker.internal:3013']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'tracseq-sample-service'
    static_configs:
      - targets: ['host.docker.internal:3011']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'tracseq-api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Infrastructure Services
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Health Checks
  - job_name: 'tracseq-health-checks'
    static_configs:
      - targets: 
          - 'host.docker.internal:3010'
          - 'host.docker.internal:3011' 
          - 'host.docker.internal:3013'
          - 'host.docker.internal:8000'
    metrics_path: '/health'
    scrape_interval: 15s
    scrape_timeout: 5s