global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'tracseq-microservices'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # TracSeq Microservices
  - job_name: 'tracseq-auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'tracseq-sample-service'
    static_configs:
      - targets: ['sample-service:8081']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'tracseq-enhanced-storage-service'
    static_configs:
      - targets: ['enhanced-storage-service:8082']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'tracseq-template-service'
    static_configs:
      - targets: ['template-service:8083']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'tracseq-sequencing-service'
    static_configs:
      - targets: ['sequencing-service:8084']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'tracseq-notification-service'
    static_configs:
      - targets: ['notification-service:8085']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'tracseq-enhanced-rag-service'
    static_configs:
      - targets: ['enhanced-rag-service:8086']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'tracseq-event-service'
    static_configs:
      - targets: ['event-service:8087']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'tracseq-transaction-service'
    static_configs:
      - targets: ['transaction-service:8088']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'tracseq-api-gateway'
    static_configs:
      - targets: ['api-gateway:8089']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Infrastructure Services
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Health checks for services
  - job_name: 'tracseq-health-checks'
    static_configs:
      - targets: 
        - 'auth-service:8080'
        - 'sample-service:8081'
        - 'enhanced-storage-service:8082'
        - 'template-service:8083'
        - 'sequencing-service:8084'
        - 'notification-service:8085'
        - 'enhanced-rag-service:8086'
        - 'event-service:8087'
        - 'transaction-service:8088'
        - 'api-gateway:8089'
    scrape_interval: 30s
    metrics_path: /health
    scheme: http
    params:
      format: ['prometheus']

  # Blackbox exporter for external service monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:8089/health
        - http://auth-service:8080/health
        - http://sample-service:8081/health
        - http://enhanced-storage-service:8082/health
        - http://template-service:8083/health
        - http://sequencing-service:8084/health
        - http://notification-service:8085/health
        - http://enhanced-rag-service:8086/health
        - http://event-service:8087/health
        - http://transaction-service:8088/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: tracseq-blackbox-exporter:9115