# Minimal Mimir config for single-process mode
target: all

server:
  http_listen_port: 9009

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/mimir

ingester:
  ring:
    replication_factor: 1

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/mimir/blocks

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/mimir/ruler

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /data/mimir/alertmanager

limits:
  # Limit max number of samples per query
  max_fetched_series_per_query: 10000
