apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Jaeger
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger-uid
          urlDisplayLabel: "View Trace"

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    uid: loki-uid
    jsonData:
      httpMethod: GET
      derivedFields:
        - datasourceUid: jaeger-uid
          matcherRegex: '(?:trace_id|traceID)=(\w+)'
          name: trace_id
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'

  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    uid: jaeger-uid
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki-uid
        filterByTraceID: true
        filterBySpanID: true
        tags:
          - key: service_name
            value: service
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'