apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  namespace: tracseq
  labels:
    app.kubernetes.io/name: chromadb
    app.kubernetes.io/component: chromadb
    app.kubernetes.io/part-of: tracseq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chromadb
      app.kubernetes.io/component: chromadb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chromadb
        app.kubernetes.io/component: chromadb
        app.kubernetes.io/part-of: tracseq
    spec:
      serviceAccountName: default
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: chromadb
        image: chromadb/chroma:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: IS_PERSISTENT
          value: "TRUE"
        - name: PERSIST_DIRECTORY
          value: "/chroma/data"
        - name: ANONYMIZED_TELEMETRY
          value: "FALSE"
        - name: ALLOW_RESET
          value: "FALSE"
        - name: CHROMA_SERVER_AUTH_PROVIDER
          value: "chromadb.auth.token.TokenAuthServerProvider"
        - name: CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER
          value: "chromadb.auth.token.TokenConfigServerAuthCredentialsProvider"
        - name: CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER
          value: "AUTHORIZATION"
        - name: CHROMA_SERVER_AUTH_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: chromadb-auth-token
              key: token
        volumeMounts:
        - name: chromadb-data
          mountPath: /chroma/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: chromadb-data
        persistentVolumeClaim:
          claimName: chromadb-pvc
---
apiVersion: v1
kind: Secret
metadata:
  name: chromadb-auth-token
  namespace: tracseq
type: Opaque
stringData:
  token: "CHANGE_ME_IN_PRODUCTION_USE_SECURE_TOKEN"  # Will be replaced by deployment script