global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'enhanced-rag-service'
    static_configs:
      - targets: ['enhanced-rag-service:8086']
    metrics_path: '/metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
