version: '3.8'

# TracSeq 2.0 - Build All Microservices
# Use this file to build and run all microservices together

networks:
  tracseq_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  postgres_data:
  redis_data:
  ollama_data:
  prometheus_data:
  grafana_data:

services:
  # Infrastructure
  postgres:
    image: postgres:15-alpine
    container_name: tracseq-postgres
    environment:
      POSTGRES_DB: tracseq_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tracseq_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tracseq_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tracseq-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - tracseq_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    container_name: tracseq-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - tracseq_network

  # Core Services
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    image: tracseq-config-service:latest
    container_name: tracseq-config-service
    ports:
      - "8091:8091"
    environment:
      - PORT=8091
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      postgres:
        condition: service_healthy

  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    image: tracseq-auth-service:latest
    container_name: tracseq-auth-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=tracseq-jwt-secret-change-in-production
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  sample-service:
    build:
      context: ./sample_service
      dockerfile: Dockerfile
    image: tracseq-sample-service:latest
    container_name: tracseq-sample-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service

  enhanced-storage-service:
    build:
      context: ./enhanced_storage_service
      dockerfile: Dockerfile
    image: tracseq-enhanced-storage-service:latest
    container_name: tracseq-enhanced-storage-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service

  template-service:
    build:
      context: ./template_service
      dockerfile: Dockerfile
    image: tracseq-template-service:latest
    container_name: tracseq-template-service
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service

  sequencing-service:
    build:
      context: ./sequencing_service
      dockerfile: Dockerfile
    image: tracseq-sequencing-service:latest
    container_name: tracseq-sequencing-service
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service
      - sample-service

  notification-service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    image: tracseq-notification-service:latest
    container_name: tracseq-notification-service
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service

  event-service:
    build:
      context: ./event_service
      dockerfile: Dockerfile
    image: tracseq-event-service:latest
    container_name: tracseq-event-service
    ports:
      - "8087:8087"
    environment:
      - PORT=8087
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service

  transaction-service:
    build:
      context: ./transaction_service
      dockerfile: Dockerfile
    image: tracseq-transaction-service:latest
    container_name: tracseq-transaction-service
    ports:
      - "8088:8088"
    environment:
      - PORT=8088
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service
      - event-service

  library-details-service:
    build:
      context: ./library_details_service
      dockerfile: Dockerfile
    image: tracseq-library-details-service:latest
    container_name: tracseq-library-details-service
    ports:
      - "8092:8092"
    environment:
      - PORT=8092
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service

  qaqc-service:
    build:
      context: ./qaqc_service
      dockerfile: Dockerfile
    image: tracseq-qaqc-service:latest
    container_name: tracseq-qaqc-service
    ports:
      - "8093:8093"
    environment:
      - PORT=8093
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service

  spreadsheet-versioning-service:
    build:
      context: ./spreadsheet_versioning_service
      dockerfile: Dockerfile
    image: tracseq-spreadsheet-versioning-service:latest
    container_name: tracseq-spreadsheet-versioning-service
    ports:
      - "8094:8094"
    environment:
      - PORT=8094
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - AUTH_SERVICE_URL=http://auth-service:8080
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - auth-service

  # AI/ML Services
  enhanced-rag-service:
    build:
      context: ./enhanced_rag_service
      dockerfile: Dockerfile
    image: tracseq-enhanced-rag-service:latest
    container_name: tracseq-enhanced-rag-service
    ports:
      - "8086:8086"
    environment:
      - PORT=8086
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/tracseq_db
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONUNBUFFERED=1
    networks:
      - tracseq_network
    depends_on:
      - postgres
      - redis
      - ollama

  lab-submission-rag:
    build:
      context: ./lab_submission_rag
      dockerfile: Dockerfile
    image: tracseq-lab-submission-rag:latest
    container_name: tracseq-lab-submission-rag
    ports:
      - "8095:8095"
    environment:
      - PORT=8095
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/tracseq_db
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONUNBUFFERED=1
    volumes:
      - ./lab_submission_rag/uploads:/app/uploads:rw
      - ./lab_submission_rag/exports:/app/exports:rw
    networks:
      - tracseq_network
    depends_on:
      - postgres
      - redis
      - ollama

  # Gateway
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    image: tracseq-api-gateway:latest
    container_name: tracseq-api-gateway
    ports:
      - "8089:8089"
    environment:
      - PORT=8089
      - AUTH_SERVICE_URL=http://auth-service:8080
      - SAMPLE_SERVICE_URL=http://sample-service:8081
      - ENHANCED_STORAGE_SERVICE_URL=http://enhanced-storage-service:8082
      - TEMPLATE_SERVICE_URL=http://template-service:8083
      - SEQUENCING_SERVICE_URL=http://sequencing-service:8084
      - NOTIFICATION_SERVICE_URL=http://notification-service:8085
      - ENHANCED_RAG_SERVICE_URL=http://enhanced-rag-service:8086
      - EVENT_SERVICE_URL=http://event-service:8087
      - TRANSACTION_SERVICE_URL=http://transaction-service:8088
      - CONFIG_SERVICE_URL=http://config-service:8091
      - LIBRARY_DETAILS_SERVICE_URL=http://library-details-service:8092
      - QAQC_SERVICE_URL=http://qaqc-service:8093
      - SPREADSHEET_VERSIONING_SERVICE_URL=http://spreadsheet-versioning-service:8094
      - LAB_SUBMISSION_RAG_URL=http://lab-submission-rag:8095
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=tracseq-jwt-secret-change-in-production
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    networks:
      - tracseq_network
    depends_on:
      - auth-service
      - sample-service
      - enhanced-storage-service
      - template-service
      - sequencing-service
      - notification-service
      - enhanced-rag-service
      - event-service
      - transaction-service
      - library-details-service
      - qaqc-service
      - spreadsheet-versioning-service
      - lab-submission-rag

  lab-manager:
    build:
      context: ./lab_manager
      dockerfile: Dockerfile
    image: tracseq-lab-manager:latest
    container_name: tracseq-lab-manager
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracseq_db
      - API_GATEWAY_URL=http://api-gateway:8089
      - RUST_LOG=info
    networks:
      - tracseq_network
    depends_on:
      - api-gateway

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: tracseq-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    networks:
      - tracseq_network

  grafana:
    image: grafana/grafana:latest
    container_name: tracseq-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - tracseq_network
    depends_on:
      - prometheus 
