version: '3.8'

services:
  template-service:
    build: .
    container_name: template-service
    ports:
      - "8083:8083"
    environment:
      - RUST_LOG=info
      - SERVICE_PORT=8083
    networks:
      - template-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  template-network:
    driver: bridge 
