http.host: "0.0.0.0"
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Pipeline configuration
path.config: /usr/share/logstash/pipeline
config.reload.automatic: true
config.reload.interval: 3s

# Logging
log.level: info
path.logs: /usr/share/logstash/logs

# Performance tuning
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Queue settings
queue.type: persisted
queue.max_bytes: 1gb
queue.drain: true

# Dead letter queue
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 100mb 