metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

metricbeat.modules:
  # System metrics
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - uptime
      - socket_summary
      - filesystem
      - fsstat
    enabled: true
    period: 10s
    processes: ['.*']
    cpu.metrics: ["percentages", "normalized_percentages"]
    core.metrics: ["percentages"]

  # Docker metrics
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - image
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  # Elasticsearch metrics
  - module: elasticsearch
    metricsets:
      - node
      - node_stats
      - cluster_stats
    period: 10s
    hosts: ["http://elasticsearch:9200"]
    enabled: true

  # Logstash metrics
  - module: logstash
    metricsets:
      - node
      - node_stats
    period: 10s
    hosts: ["http://logstash:9600"]
    enabled: true

  # Kibana metrics
  - module: kibana
    metricsets:
      - status
    period: 10s
    hosts: ["http://kibana:5601"]
    enabled: true

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_fields:
      target: ''
      fields:
        environment: development
        system: tracseq

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "tracseq-metricbeat-%{+yyyy.MM.dd}"
  template.name: "tracseq-metricbeat"
  template.pattern: "tracseq-metricbeat-*"

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

setup.kibana:
  host: "kibana:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644

name: tracseq-metricbeat
tags: ["tracseq", "laboratory", "metrics"] 