#!/bin/bash

echo "Instructions to fix remaining SQLx compile-time macros:"
echo ""
echo "The following SQLx macros need to be replaced with runtime equivalents:"
echo ""
echo "1. Replace query_as! with query_as and FromRow derive"
echo "   - Add #[derive(sqlx::FromRow)] to StoredBarcode struct"
echo "   - Change: sqlx::query_as!(StoredBarcode, \"SELECT * FROM barcodes WHERE barcode = \$1\", barcode)"
echo "   - To: sqlx::query_as::<_, StoredBarcode>(\"SELECT * FROM barcodes WHERE barcode = \$1\").bind(barcode)"
echo ""
echo "2. Replace remaining query_scalar! macros"
echo "   - Change: sqlx::query_scalar!(\"SELECT COUNT(*) FROM barcodes\")"
echo "   - To: sqlx::query_scalar::<_, i64>(\"SELECT COUNT(*) FROM barcodes\")"
echo ""
echo "3. For nullable results, use Option<T>"
echo "   - Change: sqlx::query_scalar!(\"SELECT barcode FROM barcodes ORDER BY created_at DESC LIMIT 1\")"
echo "   - To: sqlx::query_scalar::<_, Option<String>>(\"SELECT barcode FROM barcodes ORDER BY created_at DESC LIMIT 1\")"
echo ""
echo "To apply these fixes manually:"
echo "1. Open lims-core/barcode_service/src/service.rs"
echo "2. Replace all remaining query_scalar! macros with query_scalar"
echo "3. Replace query_as! with query_as"
echo "4. Add type annotations where needed"
echo ""
echo "Alternatively, you can disable compile-time checking by setting:"
echo "export SQLX_OFFLINE=true" 